// <auto-generated />
namespace HalisahaFormamSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class New3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New3));
        
        string IMigrationMetadata.Id
        {
            get { return "201405200837272_New3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
